### ISSUE TITLE
Improvement: Reduce the number of Rake tasks needed

### ISSUE THREAD

**Issue by natemccurdy** [puppetlabs/puppet_litmus#106]
Right now one has to run 5 different rake tasks to perform a full test and teardown:

```
pdk bundle exec rake 'litmus:provision[docker, centos:7]'
pdk bundle exec rake 'litmus:install_agent[puppet]'
pdk bundle exec rake 'litmus:install_module'
pdk bundle exec rake 'litmus:acceptance:parallel'
pdk bundle exec rake 'litmus:tear_down'
```

The user experience could be improved by reducing that number down to 1 or 2 in the cases where they just want to quickly spin up and a box and run a test.

And for CI systems where you need to pass a set of commands to run... it's simpler to pass 1 command rather than [an array of 5](https://github.com/natemccurdy/yumrepos_fact/blob/87b4919d8f955dc7094ba119cc27b111c71089d8/.travis.yml#L28).

And maybe this bit is a stretch goal, but having a `litmus` command that abstracts away all of the Rake commands could be a good thing. Especially for users that just want to test some Puppet code but don't necessarily want to get deep into the Ruby ecosystem and might be scared off by `bundle install` and `bundle exec`. Things really do get complicated _very quickly_ in the bundler world as I'm sure you all know.

**Comment by tphoney** [comment]
Hey ! thanks for the feedback. 
I agree with you, it does feel like a lot of steps. And for an automated CI system it is a pain. maybe something like `litmus:just_do_it[release_checks, puppet6]` which calls provision_list uses [a yaml file ](https://github.com/puppetlabs/puppetlabs-motd/blob/master/provision.yaml ) to provision multiple systems then install_agent / install_module / acceptance parallel then tear down.

On your stretch goal, the aim for litmus is to move into the PDK (possibly, its own cli) giving that user experience to first time users. At the minute it is very much aimed at people comfortable with rake, and all that comes with it.

**Comment by tphoney** [comment]
Hi @natemccurdy does #128 give what you want ?

**Comment by natemccurdy** [comment]
@tphoney Cool, yeah! That should help. Thanks 👍

**Comment by tphoney** [comment]
Marking as closed
