### ISSUE TITLE
serverspec module does not represent what it actually does

### ISSUE THREAD

**Issue by logicminds** [puppetlabs/puppet_litmus#125]
This module is named [serverspec](https://github.com/puppetlabs/puppet_litmus/blob/master/lib/puppet_litmus/serverspec.rb) but it doesn't really do anything specific to serverspec.   This class should be renamed so that we can create additional spec_helper_acceptance files that use this utility module but are not serverspec based.

https://github.com/puppetlabs/puppet_litmus/blob/master/lib/puppet_litmus.rb#L14

**Comment by tphoney** [comment]
hi @logicminds. Naming is hard, any ideas of what it should be called. I'll have a think and put some in, in a wee while.

**Comment by logicminds** [comment]
Possibly acceptance_helpers.rb or test_helpers.rb.

The idea would be I would just need to include the helpers into my acceptance_helper.rb file inside my module.

**Comment by tphoney** [comment]
its been renamed by the wonderful @florindragos with #200 . I am marking this as closed.
