### ISSUE TITLE
Puppet-module-posix-default missing version

### ISSUE THREAD

**Issue by jfreymann** [puppetlabs/puppet_litmus#132]
Currently testing out puppet-litmus and ran into an interesting issue. 
Executing the following on a Mac (in the puppetlabs-motd module) 
`bundle install --path .bundle/gems/`

I get the following error 
`Could not find gem 'puppet-module-posix-default-r2.6' in any of the gem sources listed in your Gemfile.`

Looking at the Gemfile it's pulling that version from my local ruby version (2.6.3). 

I can't seem to find an updated puppet-module-posix-default gem for 2.6. Am I doing something wrong or is there any plans on supporting 2.6?

**Comment by jfreymann** [comment]
Using rbenv so I'll install 2.5 to continue testing.

**Comment by tphoney** [comment]
Hey @jfreymann great to hear from you. This will take a little explaining. 
The latest puppet agent still only supports ruby 2.5. Puppet modules use the puppet-modules-gems library, it only goes up to 2.5 as well https://github.com/puppetlabs/puppet-module-gems/blob/master/config/dependencies.yml#L4-L8 
So it isnt a litmus thing at all. Sorry about the hassle.
