### ISSUE TITLE
Unclear message when trying to provision with an undefined provision list

### ISSUE THREAD

**Issue by timidri** [puppetlabs/puppet_litmus#190]
## Describe the Bug
When I try to provision hosts using a non-existent provision list, the error message is unclear.

## Expected Behavior
I expect litmus to tell me something like 'The provision list <i_dont_exist> does not exist`

## Steps to Reproduce
1. Make sure you have a valid provision.yaml file which does not contain a list called `i_dont_exist`
2. Execute `bundle exec rake 'litmus:provision_list[i_dont_exist]'`

You will receive output like so:
```
rake aborted!
NoMethodError: undefined method `[]' for nil:NilClass
/Users/dimitri.tischenko/git/meltdown/.bundle/gems/ruby/2.6.0/bundler/gems/puppet_litmus-d30865d66496/lib/puppet_litmus/rake_tasks.rb:109:in `block (2 levels) in <top (required)>'
/Users/dimitri.tischenko/git/meltdown/.bundle/gems/ruby/2.6.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/Users/dimitri.tischenko/.rbenv/versions/2.6.1/bin/bundle:23:in `load'
/Users/dimitri.tischenko/.rbenv/versions/2.6.1/bin/bundle:23:in `<main>'
Tasks: TOP => litmus:provision_list
(See full trace by running task with --trace)
```

## Environment
 - Version [puppet_litmus-d30865d66496]
 - Platform [MacOS 10.14.6 / ruby 2.6.1p33]

**Comment by tphoney** [comment]
does #195 help ?

**Comment by tphoney** [comment]
There is some rudimentary error checking now, with a friendlier error. Thanks for the ticket @timidri 

It is in master, not released as of 3rd October

**Comment by timidri** [comment]
@tphoney that should absolutely help, thank you!
