### ISSUE TITLE
Rake support for inventory v2

### ISSUE THREAD

**Issue by abuxton** [puppetlabs/puppet_litmus#229]
## Use Case
Bolt inventory as released a V2, the rake command that dynamically generates `litmus:acceptance:<name>` does not support target or uri.
Additionally it would be awesome to be able to test across groups in this way too
## Describe the Solution You Would Like
support for v2 target key
support for a generated rake task to be able to execute `litmus:acceptance:group`

## Describe Alternatives You've Considered
NA

**Comment by tphoney** [comment]
I am going to have a look at this today. : ) 
It annoys me too.

**Comment by DavidS** [comment]
@tphoney now implemented v2 support throughout litmus and the provison tasks - does this need more work then?
