### ISSUE TITLE
[Feature] Remove dependency on PDK

### ISSUE THREAD

**Issue by glennsarti** [puppetlabs/puppet_litmus#234]
## Use Case
Currently litmus pulls in the entire PDK library purely to build a module.  As this is such a simple task, the code should be copied from PDK, and once proven, available as a separate gem to be consumed by the PDK and Litmus

## Describe the Solution You Would Like
Remove dependency on PDK and vendor the code.

## Describe Alternatives You've Considered

Keep the PDK dependency - This creates a horrible situation where the PDK calls litmus which calls PDK.  Also a lot of "bloat" for a simple single task.

## Additional Context
N/A

**Comment by DavidS** [comment]
This was shipped in 0.16.0
