### ISSUE TITLE
Proposals for docs improvement

### ISSUE THREAD

**Issue by findmyname666** [puppetlabs/puppet_litmus#245]
1) Add steps how to add litmus support for a new module/repository.
2) Missing info that the Rakefile should contain `require 'puppetlabs_spec_helper/rake_tasks'`. Therefore it will fail:
```
rake aborted!
Don't know how to build task 'spec_prep' (See the list of available tasks with `rake --tasks`)
/home/iser/.rvm/gems/ruby-2.5.3/gems/puppet_litmus-0.15.0/lib/puppet_litmus/rake_tasks.rb:72:in `block (2 levels) in <top (required)>'
/home/findmyname/.rvm/gems/ruby-2.5.3/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/home/findmyname/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `eval'
/home/findmyname/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => litmus:provision
```
3) Documentation mention two different names of docker images.
- [waffleimage](https://github.com/puppetlabs/puppet_litmus/wiki/Overview-of-Litmus#provision)
- [litmusimage](https://github.com/puppetlabs/litmusimage/blob/master/README.md)

Pls unify it or specify differences.

4) Documentation doesn't mention whether limus can be used for testing of code repository e.g. whole Puppet codebase.

**Comment by DavidS** [comment]
Hi @findmyname666 ,

I'm currently working on addressing this and a few other documentation issues. Going through your report, I don't quite understand the last part, can you elaborate what you mean by "code repository e.g. whole Puppet codebase."?

**Comment by findmyname666** [comment]
> Going through your report, I don't quite understand the last part, can you elaborate what you mean by "code repository e.g. whole Puppet codebase."?

Litmus is mainly used for testing of modules right ? but my point was whether it can be used for test of whole Puppet code base e.g. your all manifests, profiles, roles ... something like [onceover](https://github.com/dylanratcliffe/onceover) project.

**Comment by trevor-vaughan** [comment]
@findmyname666 I don't see why not. They're all just modules when you remove the names and techniques.

**Comment by findmyname666** [comment]
@trevor-vaughan so yeaah ... it would be cool to have some mention about that in DOC + some procedure that it really works e.g. that was my point. I'm leave decision up to you ;)

**Comment by trevor-vaughan** [comment]
Hmm....I think that it may be better to clear up the misconception between modules, roles, profiles, and control repos.

They're logical constructs and everything is either an entry point (site.pp, control repo, bolt) or it's a module (role, profile, regular module).

Taking the mystery out of some of this may reduce confusion in testing.

Feed it Hiera, put it in the right spot, it'll work.
