### ISSUE TITLE
being able to have a display with verbose mode

### ISSUE THREAD

**Issue by Dan33l** [puppetlabs/puppet_litmus#256]
## Use Case
I am trying a get in touch with Litmus, but i am yet using Beaker. My today issue is to get a display of what happened in detail with a failing `puppet apply` during `bundle exec rake litmus:acceptance:parallel`

## Describe the Solution You Would Like
With Beaker, it exists a variable `BEAKER_debug` that permits to get a `puppet apply --verbose`. The possibility to check details of run looks for me an important feature. When you know the time necessary to run acceptance tests, if you can not get the information required to know the root of the fail, it is lost time.

I would like to have displayed output of `puppet apply --verbose` instead of the spinners

**Comment by florindragos** [comment]
Hey @Dan33l 
Have you tried using `RSPEC_DEBUG` ?
https://github.com/puppetlabs/puppet_litmus/blob/master/lib/puppet_litmus/puppet_helpers.rb#L20

**Comment by Dan33l** [comment]
I tested but it is not what i am expecting for two reasons.
* it provides run in `--debug` mode, i am expecting `--verbose`.
* it requires to launch function with flag `debug`. When you are working on a module, it is not convenient to have to modify the code for this. Only using a variable should be enough to enable/disable the verbose output.

In my day to day usage of acceptance tests, it's really exceptional to need the debug mode. And exceptionally it looks possible to modify the code to get debug. But the verbose mode looks to be a for me a must have.

**Comment by jordanbreen28** [comment]
Hey @Dan33l.

Apologies for the lack of engagement on this.. I have been tasked with auditing the ageing issues on this repo.
Due to the age of this issue, I am voting to close.

Please re-open if you would still like to keep this feature request, so it can remain visible.
