### ISSUE TITLE
Why does the Litmus gemspec reference the docker-api gem?

### ISSUE THREAD

**Issue by glennsarti** [puppetlabs/puppet_litmus#257]
## Describe the Bug
The litmus gemspec specifies the docker-api gem, however there is no code in Litmus which actually uses the docker-api gem.  Why is this here?

## Expected Behavior
Gemspec should only specify what this gem needs

**Comment by DavidS** [comment]
@florindragos @tphoney any ideas? is that gem required for the `provision` module, or is this just a hold-off from previous experiments?

**Comment by tphoney** [comment]
this was being used by the docker_exp provisioner, this can likely dissappear. Assuming it doesnt break that provisioner

**Comment by florindragos** [comment]
This was added when the bolt docker transport went from docker-api to docker cli imlementation. 
specinfra needs the docker-api gem when using the docker backend.
