### ISSUE TITLE
Allow install_module rake tasks to set module_repository

### ISSUE THREAD

**Issue by jmangt** [puppetlabs/puppet_litmus#259]
## Use Case
Litmus is unable to install modules from a private forge repository (Artifactory). 

## Describe the Solution You Would Like
Allow `rake install_module` to accept a `module_repository` argument that defaults to `https://forgeapi.puppetlabs.com`

## Describe Alternatives You've Considered
Updating the global puppet.conf file. This will imply creating a separate bolt task to bootstrap the platform and it will lock the vm image to only work with one  repository.

**Comment by michaeltlombardi** [comment]
@jmangt currently the `install_module` task builds the working directory module, copies the tar to the target node, then runs `puppet module install <path_to_uploaded_tar>`.

What you're looking for might be better handled by `install_module_from_directory` which you point at a folder (by default, `./spec/fixtures/modules` to build the modules, upload, and install. You can define what modules end up there via the [`fixtures.yml`](https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures) definition. I _suspect_ you'll need to include dependencies there which can't be found on the forge, but I'm not _sure_.

**Comment by jmangt** [comment]
I will try that alternative. I have submitted https://github.com/puppetlabs/puppet_litmus/pull/260 for your consideration.
