### ISSUE TITLE
install_modules_from_directory only keeps and installs the last module built

### ISSUE THREAD

**Issue by zenitraM** [puppetlabs/puppet_litmus#270]
## Describe the Bug
This is probably connected to #246 - if you have a module that has more than a single dependency, once SSH is working correctly (which gets fixed by #247) only one of the modules gets uploaded and installed.

This seems to be due to the following code:
https://github.com/puppetlabs/puppet_litmus/blob/bfaa737766d912ad66494dbc945552375e25c4bd/lib/puppet_litmus/rake_helper.rb#L109-L122

On every module that gets built, the `target_dir` folder (Dir.pwd + `pkg`) folder gets removed so that only the last module remains at that folder at the end of the folder. That directory probably should only be removed (if it must be removed at all?) before starting building all the modules.

## Steps to Reproduce
Try to run 
```
pdk bundle exec rake 'litmus:install_modules_from_directory[spec/fixtures/modules]'
``` 
with more than one module on `spec/fictures/modules
Only one module gets uploaded + installed (also no feedback is displayed to the user)

## Environment
Release `0.17.0`

**Comment by DavidS** [comment]
#247 has a fix for this now, would be great if you can confirm in your environment.

**Comment by zenitraM** [comment]
This works now, thanks! (and sorry for the delay!)
