### ISSUE TITLE
The litmusimage's mentioned under "Testing services" is missing ':' before the tag

### ISSUE THREAD

**Issue by reenberg** [puppetlabs/puppet_litmus#276]
## Describe the Change You Would Like
Page: [https://github.com/puppetlabs/puppet_litmus/wiki/Overview-of-Litmus](https://github.com/puppetlabs/puppet_litmus/wiki/Overview-of-Litmus#testing-services)
Heading: Testing services

The list of litmusimage's mentioned is missing a ':' between the image name and the tags.

**Comment by DavidS** [comment]
Fixed in https://github.com/puppetlabs/puppet_litmus/wiki/Overview-of-Litmus/_compare/3459fbd1e52911ab3a6a71ec386e2b32ea6a3098...6753dfeadd1bf73e59f88a682e83b5ac6389e506 

thanks for reporting!
