### ISSUE TITLE
Litmus exits cleanly when there are errors with `install_module`

### ISSUE THREAD

**Issue by lswith** [puppetlabs/puppet_litmus#285]
## Describe the Bug
When running `install_module` against my host:
```
pdk (INFO): Using Ruby 2.5.7
pdk (INFO): Using Puppet 6.13.0
Libhoney::Client: no writekey configured, disabling sending events
Built
127.0.0.1:2200 failed {"stdout"=>"\e[mNotice: Preparing to install into /etc/puppetlabs/code/environments/production/modules ...\e[0m\n\e[mNotice: Downloading from https://forgeapi.puppet.com ...\e[0m\n", "stderr"=>"\e[1;31mError: Could not install module 'REDACTED' (???)\n  No version of 'REDACTED' can satisfy all dependencies\n    Use `puppet module install --ignore-dependencies` to install only this module\e[0m\n", "exit_code"=>1, "_error"=>{"kind"=>"puppetlabs.tasks/command-error", "issue_code"=>"COMMAND_ERROR", "msg"=>"The command failed with exit code 1", "details"=>{"exit_code"=>1}}}
Installed
➜   ✗ echo $?
0
```

## Expected Behavior
I would expect `install_module` to exit with a 1 or above when an error occurs installing the module.

## Environment
 - Version master
 - Platform Vagrant Ubuntu 16.04

**Comment by DavidS** [comment]
What version of litmus is that? We've released changes this week to address this and with 0.18 and onwards you should get proper errors from that. (via #247)

**Comment by lswith** [comment]
It was an old version. I've updated and I'm checking if this is still an issue.

**Comment by lswith** [comment]
Yep, it works as expected now with the latest version.
