### ISSUE TITLE
Can't determine how to have Litmus ignore my keyring

### ISSUE THREAD

**Issue by trevor-vaughan** [puppetlabs/puppet_litmus#287]
## Describe the Bug
When using trying to run the litmus tests via vagrant in the puppetlabs-motd module, the initial provision step is failing with a 'too many failed connections' error.

This is due to having a large set of keys in my SSH keyring for various testing systems.

## Expected Behavior
The connection should succeed

## Steps to Reproduce
1. Add more than 6 keys to your keyring
2. Try to run the Vagrant tests against CentOS

**Comment by DavidS** [comment]
* Can you successfully run a `bolt command run` against the vagrant box? 
* If no, can you get it to work using the [ssh options](https://puppet.com/docs/bolt/latest/bolt_configuration_reference.html#ssh) in the `inventory.yml`?

**Comment by jordanbreen28** [comment]
Hey @trevor-vaughan!
I am going to go ahead and close this ageing issue, please re-open if necessary.
Thanks
