### ISSUE TITLE
Support Bolt Plugins

### ISSUE THREAD

**Issue by lswith** [puppetlabs/puppet_litmus#288]
## Use Case

I am currently using the bolt `terraform` plugin for the inventory.yaml file. I would like to be able to use this plugin when using the rake tasks: `install_agent`, `install_module`, and `acceptance:parallel`. 

## Describe the Solution You Would Like
I would expect the pdk to ship with the terraform plugin or it simply be added to the .fixtures.yml file. I would then expect the `find_targets` function to use `bolt` to resolve the targets necessary.

## Describe Alternatives You've Considered
Without this functionality, the provisioner would need to completely handle provisioning terraform, or I will have to generate an `inventory.yaml` file which better conforms to litmus' current functionality.

## Additional Context

For testing this, simply add:
```
    terraform: 'puppetlabs/terraform'
    ruby_task_helper: 'puppetlabs/ruby_task_helper'
    ruby_plugin_helper: 'puppetlabs/ruby_plugin_helper'
```
to the `.fixtures.yml` in the module.

Make sure to use a terraform bolt group within the `inventory.yaml` file and that the `inventory.yaml` file works with the packaged version of bolt.

**Comment by DavidS** [comment]
This is now possible. We even have a short demo on using terraform as a provisioner using the terraform task from the module: https://www.youtube.com/watch?v=8BMo9DcZ4-Q
