### ISSUE TITLE
Failed to install litmus

### ISSUE THREAD

**Issue by johnqa** [puppetlabs/puppet_litmus#289]
Hi, I am trying to install litmus on a workstation which doesn't have direct access to internet but has access to an internal mirror of all rubygems.

Running the command: "C:\Program files\Puppet Labs\Puppet\puppet\bin\gem.bat" install puppet_litmus

After having a multitude of gems installed i get:
```
Building native extensions. This could take a while...
ERROR:  Error installing puppet_litmus:
        ERROR: Failed to build gem native extension.

    current directory: C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.5.0/gems/http-parser-1.2.1/ext
"C:/Program Files/Puppet Labs/Puppet/puppet/bin/ruby.exe" -rrubygems C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.5.0/gems/rake-12.3.0/exe/rake RUBYARCHDIR="C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.5.0/extensions/x64-mingw32/2.5.0/http-parser-1.2.1" RUBYLIBDIR="C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.5.0/extensions/x64-mingw32/2.5.0/http-parser-1.2.1"
C:/Program Files/Puppet Labs/Puppet/puppet/bin/ruby.exe: No such file or directory -- C:/Program (LoadError)

rake failed, exit code 1

Gem files will remain installed in C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.5.0/gems/http-parser-1.2.1 for inspection.
Results logged to C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.5.0/extensions/x64-mingw32/2.5.0/http-parser-1.2.1/gem_make.out
```

I am new to puppet, ruby and gems and cannot figure it out.

I have PDK 1.17.0 installed already.

Thank you,
John

**Comment by DavidS** [comment]
Thanks for writing in!

In a module created with the PDK, `pdk bundle install` will get you litmus installed (its dependencies are shipped with the pdk package) and `pdk bundle exec rake ...` will give you access to the litmus tasks.

Feel free to re-open this if it is still giving you troubles. If so, please post the full command and `--debug` log from the PDK.

**Comment by johnqa** [comment]
Hi,

Things were not so simple. I had to put the certificate in different places for 2 of the ruby versions, installed bundler:2.1.4 in 2 places, change the source in the Gemfile to point to our local mirror, and after finally having pdk bundle install working, when running a simple litmus command like pdk bundle install i have the error:
```
pdk bundle exec rake "litmus_image"
pdk (INFO): Using Ruby 2.5.7
pdk (INFO): Using Puppet 6.13.0
Traceback (most recent call last):
C:\Program Files\Puppet Labs\DevelopmentKit\private\ruby\2.5.7\bin\ruby.exe: invalid switch in RUBYOPT: -F (RuntimeError)
```
