### ISSUE TITLE
Several fixes on Converting modules to use Litmus

### ISSUE THREAD

**Issue by mfaure** [puppetlabs/puppet_litmus#290]
In [Converting modules to use Litmus](https://github.com/puppetlabs/puppet_litmus/wiki/Converting-modules-to-use-Litmus):

* Replace `1. Add code to your Gemfile and Rakefile` by  `1. Add code to your Gemfile`
* Replace `1. Add code to your Rakefile` by `2. Add code to your Rakefile`
* Re-number all following titles
* Fix markdown typo in `4. Update the spec/spec_helper_acceptance_local.rb\` file`

PS: having documentation placed as code (not wiki) would be way easier to contribute to ;)

**Comment by DavidS** [comment]
We've now switched to a jekyll microsite over on https://puppetlabs.github.io/litmus/ with a full public github repo at https://github.com/puppetlabs/litmus .

In the process of migrating, I've also fixed your suggestions. Thanks!

**Comment by mfaure** [comment]
Great move @DavidS! Thanks!
