### ISSUE TITLE
Feedback as a first time user of Litmus

### ISSUE THREAD

**Issue by mfaure** [puppetlabs/puppet_litmus#291]
## Use Case

I know a bit of Beaker but setting it up is tough, so I wanted to try Litmus on a new module (and I failed).

## Describe the Solution You Would Like

* as a FLOSS contributor, I would have loved to contribute to documentation, but it is a read-only wiki, which makes contribution cumbersome. Having the doc placed as code leveraging issues / PR / diffs would be much easier :)
* I couldn't make Litmus work with Gitlab-CI on Gitlab.com. Can we discuss / contribute to have doc on how to use Litmus with Gitlab-CI? (See #292)

## Describe Alternatives You've Considered

NA

## Additional Context

Documentation looks rather thin in the wiki. Did I miss documentation elsewhere?

**Comment by carabasdaniel** [comment]
Hi @mfaure,

There is a docs microsite for Puppet Litmus that is based on the repository [here](https://github.com/puppetlabs/litmus) 

For more documentation see the published docs here: https://puppetlabs.github.io/litmus/

**Comment by mfaure** [comment]
Thank you @carabasdaniel !

**Comment by pmcmaw** [comment]
Hey @mfaure 

I am currently grooming our issues on this repo and I am just wondering if you had any luck progressing using our documentation?

**Comment by mfaure** [comment]
Hi @pmcmaw Thanks for following up. I didn't had the opportunity to work again on Litmus since my issue. But the website mentionned by @carabasdaniel is already a great improvement. Hope this helps :)

**Comment by pmcmaw** [comment]
Fantastic. I am going to close this issue as you seem happy with the documentation provided. Please feel free to reach out if you ever need anything else. We have a few different ways we can be contacted: https://puppetlabs.github.io/iac/team/2021/01/20/reaching-out.html

Thank you for taking the time to raise this issue and also reply to me, have a lovely day.
