### ISSUE TITLE
Add 'reports' option to `apply_manifest`

### ISSUE THREAD

**Issue by ekinanp** [puppetlabs/puppet_litmus#316]
This makes it easier to test report processor modules via `puppet apply` because we can just do `puppet apply <..> --reports <reports_option>` or in code: `instance.apply_manifest(<foo>, reports: <report_processors>)`

**Comment by jordanbreen28** [comment]
Hey @ekinanp,
Sorry for the lack of engagement on this.. I am currently trying to audit our ageing issues.
From my understanding at least, I am voting to close this as `puppet apply` command does not allow for a `--reports` argument.
Ref https://www.puppet.com/docs/puppet/8/man/apply.html
Please re-open if you think I've misunderstood!

Thanks.
