### ISSUE TITLE
write_file Helper

### ISSUE THREAD

**Issue by RandomNoun7** [puppetlabs/puppet_litmus#323]
## Use Case
A test has a string variable that needs to be written to a file in an arbitrary location on the disk of a target node

## Describe the Solution You Would Like
A new puppet_helpers function called `create_file` that would take the following parameters:
String: content
String: destination
String - Optional - Linux Only: Owner
String - Optional - Linux Only: Group

## Describe Alternatives You've Considered
Currently the best way to accomplish this is to use the `create_manifest_file` helper and then use a `run_shell` helper to move the file to where I need it to be. The drawback is that this is two separate calls and I have to reimplement this double call in every repo I need it in.

Also, I can't use `run_shell` to `echo <blah> > <file>` to create a file because the escaping issues are difficult.

**Comment by DavidS** [comment]
would bolt's `upload_file` (https://www.rubydoc.info/gems/bolt/2.13.0/BoltSpec/Run#upload_file-instance_method) help? That should be available to litmus users

**Comment by RandomNoun7** [comment]
The drawback there is that if I'm starting from a string variable, I have to write out my own temp file locally first, before I can use that helper. I would like to be able to pass a String variable to Litmus directly.

**Comment by DavidS** [comment]
understood.

**Comment by trevor-vaughan** [comment]
IMO, adding a helper to wrap the file creation/deletion around bolt would be preferable to yet another(TM) file upload method.

**Comment by trevor-vaughan** [comment]
Also, allowing bolt to take a String and do the right thing would also be nice.

**Comment by DavidS** [comment]
Two acceptable (to me, non-exhaustive) ways to implement `create_file` are
* create a tempfile with the contents and pass that off to bolt's `upload_file`
* modify bolt to have a `upload_file_content` method that takes a `content` instead of a `source`

**Comment by trevor-vaughan** [comment]
You could just let `upload_file` take `content` kind of like the regular `file` resource.

**Comment by DavidS** [comment]
> You could just let `upload_file` take `content` kind of like the regular `file` resource.

that would break every single current user of `upload_file`, no?

**Comment by RandomNoun7** [comment]
I think the only way to modify the Bolt function in a way that wouldn't break everyone would be to use a new options hash key that would tell Bolt to interpret the source parameter as a content string and not a path. I just don't know if the Bolt team would actually sign off on that or not.

The implementation I had in my head in Litmus would be to use effectively the existing `manifest_file` implementation where it rights a local temp file first and then uses `upload_file`, it just wouldn't be nearly so opinionated about the final file name and the location to upload it to.

**Comment by trevor-vaughan** [comment]
`Tempfile` with an associated `at_exit` should work across the board.

**Comment by RandomNoun7** [comment]
Interestingly it looks like Bolt already has a [write_file](https://github.com/puppetlabs/bolt/blob/main/bolt-modules/boltlib/lib/puppet/functions/write_file.rb) function. If this were exposed in bolt_spec.run then it would be easy to use it for this, and probably port the `manifest_file` helper to use this instead and make that code a little more concise.

**Comment by RandomNoun7** [comment]
Disregard that last comment. I see now that the `write_file` thing corresponds to a [plan function](https://puppet.com/docs/bolt/latest/plan_functions.html#write-file) only, not a method available to the bolt executor against the transports, which is where it would need to be for boltspec to take advantage of it directly. I think rather than modifying bolt_spec, which is only intended to expose functionality directly available to Bolt Executors, that team would probably say that Litmus is the proper place to implement something like `write_file`, as indeed they have done themselves by implementing it as a function rather than a new method on the transports and exposing it to the executor.

**Comment by RandomNoun7** [comment]
I decided not to address the owner:group issue in the candidate PR since Bolt doesn't provide a direct way of dealing with it. If it becomes a problem for future users that needs to be addressed then PR's can be done to this with suggestions for how to deal with it.
