### ISSUE TITLE
Motd Litmus example not working

### ISSUE THREAD

**Issue by qs5779** [puppetlabs/puppet_litmus#349]
The motd tutorial at https://puppetlabs.github.io/litmus/Running-acceptance-tests.html is failing. I have the same results on ubuntu 20.04 and archlinux.

Step two of the tutorial, "pdk bundle install" fails as follows:
$ pdk bundle install
pdk (INFO): Using Ruby 2.5.8
pdk (INFO): Using Puppet 6.17.0
Fetching https://github.com/puppetlabs/puppet_litmus
The dependency rb-readline (= 0.5.5) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mswin32, x86-mingw32, x64-mingw32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mswin32 x86-mingw32 x64-mingw32`.
The dependency puppet-module-win-default-r2.5 (~> 0.4) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mswin32, x86-mingw32, x64-mingw32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mswin32 x86-mingw32 x64-mingw32`.
The dependency puppet-module-win-dev-r2.5 (~> 0.4) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mswin32, x86-mingw32, x64-mingw32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mswin32 x86-mingw32 x64-mingw32`.
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "puppet":
  In Gemfile:
    puppet (= 6.17.0)

    bolt (= 2.32.0) was resolved to 2.32.0, which depends on
      puppet (>= 6.18.0, <= 6.19)

## Expected Behavior
Expected gems to install.

## Steps to Reproduce
1. clone motd repo
2. run "pdk bundle install"

## Environment
$ pdk --version
1.18.1

Ubuntu 20.04
Manjaro Linux 20.2

**Comment by qs5779** [comment]
This issue is apparently related to https://tickets.puppetlabs.com/browse/PDK-1279 

My work around was to:
1. cp GEMFILE GEMFILE.tmp
2. create a gemfile that ONLY specified the gem puppet, '= 6.18.0'
3. run "pdk bundle install"
4. restore original GEMFILE
5. run "PDK_PUPPET_VERSION=6.18.0 pdk bundle install"

I will leave this open, but please feel free to close without further comment.

**Comment by carabasdaniel** [comment]
Hi @qs5779,

Thanks for the work-around specifications. 
I will close this issue for now and re-open if needed.
