### ISSUE TITLE
Using `main` as branch produces a harmless error in teat_down task

### ISSUE THREAD

**Issue by unixsurfer** [puppetlabs/puppet_litmus#378]
## Describe the Bug
After we switched from `master` to `main` branch for our puppet module, we noticed the following error for `litmus:tear_down`  rake task
```
pdk bundle exec rake litmus:tear_down
pdk (INFO): Using Ruby 2.5.8
pdk (INFO): Using Puppet 6.17.0
fatal: couldn't find remote ref refs/heads/master
127.0.0.1:2200: success
```

## Expected Behavior
The task works but we shouldn't get that error.

## Steps to Reproduce
1. Switch from `master` to `main` branch
2. Run provision tasks
```
pdk bundle exec rake litmus:provision_list[bionic]
```
3. Tear down the provisioned node
```
pdk bundle exec rake litmus:tear_down
```

## Environment
 -  pdk version 1.18.1
 -  litmus version 0.18.4
 -  Debian GNU/Linux 10 (buster)

## Additional Context
The error is harmless since the provisioned nodes are removed.

**Comment by unixsurfer** [comment]
After I removed `spec/fixtures/modules` directory I don't get that error!

**Comment by sanfrancrisko** [comment]
Hi @unixsurfer , sorry for the delay in anyone picking this up. As you already figured out, removing `spec/fixtures/modules` resolved your issue. A `bundle exec rake spec_clean && bundle exec rake spec_prep` should hopefully have done the same. This was a hangover from our effort to switch `master` -> `main` in our repos. Old references to `master` needed to be blown away locally.
