### ISSUE TITLE
Move `inventory.yaml` to `spec/fixtures/litmus-inventory.yaml`; make sure to also update your provision module

### ISSUE THREAD

**Issue by DavidS** [puppetlabs/puppet_litmus#380]
When people are using bolt for production use, and use litmus for testing, they might easily and accidentally use the same `inventory.yaml` file at the base-directory of a module or control repo.  It would be very bad as it could cause litmus to run test cases against production targets.

To avoid this, litmus should use a less risky default location for its inventory, like `spec/fixtures/litmus-inventory.yaml`

**Comment by pmcmaw** [comment]
Breaking up the tasks to do, per provisioner, this is WIP and may evolve.

### abs
- [ ] provision
- [ ] teardown
- [ ] install_agent
- [ ] install_module
- [ ] uninstall_module

### docker
- [ ] provision
- [ ] teardown
- [ ] install_agent
- [ ] install_module
- [ ] uninstall_module

### docker_exp
- [ ] provision
- [ ] teardown
- [ ] install_agent
- [ ] install_module
- [ ] uninstall_module

### vagrant
- [ ] provision
- [ ] teardown
- [ ] install_agent
- [ ] install_module
- [ ] uninstall_module

### vmpooler
- [ ] provision
- [ ] teardown
- [ ] install_agent
- [ ] install_module
- [ ] uninstall_module

### additional areas
- [ ] provision_list

**Comment by pmcmaw** [comment]
All rake tasks available: 

rake litmus:acceptance:localhost[tag]
rake litmus:acceptance:oral-vehicle.delivery.puppetlabs.net[tag]
rake litmus:acceptance:parallel[tag]                                                                  
rake litmus:add_feature[added_feature,target_node_name]                                                  
rake litmus:check_connectivity[target_node_name]                                                           
rake litmus:install_agent[collection,target_node_name]                                                    
rake litmus:install_module[target_node_name,module_repository]                                             
rake litmus:install_modules_from_directory[source,target_node_name,module_repository,ignore_dependencies]  
rake litmus:metadata                                                                                      
rake litmus:provision[provisioner,platform,inventory_vars]                                                
rake litmus:provision_install[key,collection,module_repository]                                         
rake litmus:provision_list[key]                                                                            
rake litmus:reinstall_module[target_node_name,module_repository]                                          
rake litmus:tear_down[target]                                                                             
rake litmus:uninstall_module[target_node_name,module_name]

**Comment by DavidS** [comment]
Update title for CHANGELOG to give users a chance of noticing

**Comment by pmcmaw** [comment]
Ticket progress:

Renaming the inventory.yaml file to litmus_inventory.yaml
Relocating file from the module root directory to /spec/fixtures/
Removal of vmpooler as it is deprecated
The point in this change is to avoid running tests on a live production system by accident.

This piece of work includes changes in multiple places.

pdk-templates: puppetlabs/pdk-templates#414 (merged)

awaiting a pdksync to ensure all modules have the changes in github workflows before continuing on getting the other PRs merged and litmus released:

puppet_litmus: #396
provision module: puppetlabs/provision#161

The follow PR is testing out my changes: puppetlabs/puppetlabs-testing#353

**Comment by pmcmaw** [comment]
This has now been resolved.

Changes went into the following locations and a release of puppet litmus.

puppetlabs/provision#161
puppetlabs/puppet_litmus#396
puppetlabs/pdk-templates#414
