### ISSUE TITLE
How to write JUnit RSpec results from acceptance tests?

### ISSUE THREAD

**Issue by fuero** [puppetlabs/puppet_litmus#422]
## Use Case
Please allow the use of the JUnit XML report formatter or provide documentation steps to enable this.

**Comment by sanfrancrisko** [comment]
@fuero It is possible to get JUnit XML formatting by modifying / adding the following line to the `.rspec` file in the module root dir:
```ruby
--format RspecJunitFormatter
```
See [here](https://github.com/sj26/rspec_junit_formatter#using-in-your-project-with-bundler) for more details.

However, this will not work with executing the tests in parallel mode, across multiple targets, as the STDOUT / ERR is captured and a summary printed out.

Hopefully this helps somewhat, or are you looking to see this in parallel mode too?

**Comment by fuero** [comment]
I'm currently using the litmus rake tasks and `.rspec` is managed by PDK.
Thanks for pointing out the usage of `.rspec`/`.rspec_parallel`, I'll test this with my CI scripts.

**Comment by fuero** [comment]
I'm calling `litmus` like this - this ignores the aforementioned dotfiles:
```
pdk bundle exec rake \
        "litmus:provision_list[podman]" \
        "litmus:install_agent[puppet7]" \
        spec_prep \
        litmus:install_modules_from_directory
pdk bundle exec rake \
        "litmus:acceptance:parallel[podman]"
```
I'll try without PDK later, but I'd expect this to work with it.

**Comment by fuero** [comment]
PDK or no PDK, makes no difference.

**Comment by sanfrancrisko** [comment]
Hi @fuero 

So, when setting the the `.rspec` file to be this:
```rb
--format RspecJunitFormatter
```

...and then provisioning a target and running in serial mode:
```sh
# Using puppetlabs/puppetlabs-motd module

bundle exec rake 'litmus:provision_list[default]'
bundle exec rake 'litmus:install_agent'
bundle exec rake 'litmus:install_module'
bundle exec rake litmus:acceptance:localhost:2225
```

Output to `STDOUT/ERR`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="rspec" tests="6" skipped="0" failures="0" errors="0" time="24.408630" timestamp="2021-08-09T10:55:16+01:00" hostname="Ciarans-MacBook-Pro.local">
<properties>
<property name="seed" value="34966"/>
</properties>
<testcase classname="spec.acceptance.motd_spec" name="Message of the day when static message from content is expected to contain &quot;Hello world!\n&quot;" file="./spec/acceptance/motd_spec.rb" time="5.359313"></testcase>
<testcase classname="spec.acceptance.motd_spec" name="Message of the day when static message from template is expected to contain &quot;Test Template for Rspec&quot;" file="./spec/acceptance/motd_spec.rb" time="4.139811"></testcase>
<testcase classname="spec.acceptance.motd_spec" name="Message of the day when static message from content in /etc/issue is expected to contain &quot;Hello world!\n&quot;" file="./spec/acceptance/motd_spec.rb" time="3.784956"></testcase>
<testcase classname="spec.acceptance.motd_spec" name="Message of the day when static message from template in /etc/issue is expected to contain &quot;Test Template for Rspec&quot;" file="./spec/acceptance/motd_spec.rb" time="3.538575"></testcase>
<testcase classname="spec.acceptance.motd_spec" name="Message of the day when static message from content in /etc/issue.net is expected to contain &quot;Hello world!\n&quot;" file="./spec/acceptance/motd_spec.rb" time="3.625708"></testcase>
<testcase classname="spec.acceptance.motd_spec" name="Message of the day when static message from template in /etc/issue.net is expected to contain &quot;Test Template for Rspec&quot;" file="./spec/acceptance/motd_spec.rb" time="3.953746"></testcase>
</testsuite>
```

However, in parallel mode (`bundle exec rake litmus:acceptance_parallel`), this won't display as the the output is captured and a summary displayed:

```sh
┌ [✔] Running against 1 targets.
└── [✔] localhost:2225, litmusimage/centos:7
================
localhost:2225, litmusimage/centos:7
......

Finished in 25 seconds (files took 2.29 seconds to load)
6 examples, 0 failures


pid 9562 exit 0
Successful on 1 nodes: ["localhost:2225, litmusimage/centos:7"]
Checking connectivity for ["localhost:2225"]
Connectivity check PASSED.
```

In theory, just setting up the `.rspec` file in the module root should work, as parallel mode is still executing each provisioned host in the same manner, collating the results and outputting a summary. 

The potential solution for this might be to add an option to output this data in parallel mode. Let me have a look in to this and chat with the team to see what the best way forward might be.

One option I was trying to test was to use the `--out FILENAME` option to see if a workaround would be to then `cat FILENAME` after from your CI job. This will work for serial mode, but not parallel - I need to look in to what we're doing there that makes us ignore the `.rspec_parallel`. 

I'll get back to you on this.

**Comment by sanfrancrisko** [comment]
Sorry for the delay @fuero - ultimately, this will require a code change in Litmus to add support for relaying RSpec's output to the terminal when running in parallel mode. Given the team's priorities at the moment, we're not sure when we could get round to this, however, feel free to have a stab at this yourselves and we'll try to assist as best we can.

I'll close this ticket for now, but feel free to reopen if you want to use this to reference a PR to add that work.
