### ISSUE TITLE
Converting modules to use litmus documentation not working.

### ISSUE THREAD

**Issue by Tamerz** [puppetlabs/puppet_litmus#434]
On this site, there is documentation on how to start using puppet_litmus with a PDK enabled module:

https://puppetlabs.github.io/litmus/Converting-modules-to-use-Litmus.html

If I follow those instructions and try to provision:

```$ pdk bundle exec rake 'litmus:provision[docker, litmusimage/centos:7]'```

It fails with:

```Don't know how to build task 'litmus:provision' (See the list of available tasks with `rake --tasks`)```

At the top of the page, it talks about "editing or adding code" to the Gemfile and Rakefile, but then never actually gives instructions on what to edit or add.

**Comment by intothevoid1986** [comment]
@Tamerz, really shitty docs...i spent 2 days tryin' to make it works, no success...

**Comment by jordanbreen28** [comment]
Thanks for raising this @Tamerz.
I am auditing aging issues and i'm voting to close this as it should have been rectified in newer pdk releases.
please re-open if this is not the case.
