### ISSUE TITLE
Unable to run litmus:install_agent on any docker images

### ISSUE THREAD

**Issue by ffalor** [puppetlabs/puppet_litmus#441]
## Describe the Bug

Every litmus image is getting this error

```
rake litmus:install_agent
install_agent
rake aborted!
Installation of agent failed.
Results:
  localhost:52880: {"_error"=>{"details"=>{}, "kind"=>"puppetlabs.tasks/connect-error", "msg"=>"Failed to connect to localhost:52880: can't modify frozen String: \"\"", "issue_code"=>"CONNECT_ERROR"}}}

Tasks: TOP => litmus:install_agent
(See full trace by running task with --trace)
```
## Expected Behavior

It to install the puppet agent

## Steps to Reproduce

Install pdk
run `bundle install`
provision any docker image with litmus
run litmus:install_agent

## Environment
 - PDK verison 2.4.0
 - Ubuntu focal

**Comment by jordanbreen28** [comment]
Hi @ffalor,

I believe this has been resolved, so will go ahead and close this ticket.

Please go ahead and re-open if this is not the case.
