### ISSUE TITLE
can not use SUT with several network interfaces

### ISSUE THREAD

**Issue by Dan33l** [puppetlabs/puppet_litmus#60]
Since this testing tool must be able to test complex deployments, i have a use case needing several network interfaces defined on one of my SUTs.

I am talking about getting a SUT with several network devices without IP or other config, just a device. But i suppose more use cases will need a configured network link. So, IMO, both use case should be able.

**Comment by tphoney** [comment]
hi @Dan33l i am a little confused by what you mean. you want to run tests against "several network devices without IP or other config"  is a network device a switch/router/firewall or a network interface ?
If there is no IP or other config, how do you refer to them ?

**Comment by Dan33l** [comment]
The test case was to configure several network devices of a SUT Linux box with puppet. I needed network devices (for instance ens4) present (just listed in `ip link`) and not already configured  ( without IP in `ip addr`).

I hope my poor english is clearer now.

**Comment by tphoney** [comment]
Hey @Dan33l apologies for my delay in responding. 

This system under test, is it already provisioned ? do you just want to run tests against it ?

**Comment by trevor-vaughan** [comment]
Taking from my experiences, I would need something that has the current beaker Virtualbox behavior which is one cross-VM interface (eth0) and one Host access interface (eth1) that are consistently set up that way.

The ability to define additional cross-VM network interfaces would be a bonus and I think would meet the needs of @Dan33l if I'm reading things correctly.

**Comment by Dan33l** [comment]
@tphoney thank you to take care of needs.

Ah! I probably mixed the provisioning aspect with the testing aspect. 

And so yes, i would like to be able to use during tests a SUT provisioned with several interfaces (with a mac address but without ip). The tested puppet code configures ip address of several interfaces already provisioned.

**Comment by tphoney** [comment]
closing this and tracking in #72
