### ISSUE TITLE
Declare PDK as a dependency

### ISSUE THREAD

**Issue by ekohl** [puppetlabs/puppet_litmus#66]
a1a3c6701a43394d71bd74ae571931045728bef1 removed PDK as a dependency which means you can't just include puppet_litmus in your Gemfile. Is the pinning still needed?

**Comment by pmcmaw** [comment]
Hey @ekohl

This is an issue we are aware of and currently working on it. There was a release of bolt last night to update version of cri, this means we can update the version of cri in the pdk which will resolve our dependency issue that we have previously ran into. This will be resolved within the next few days.

Also it is fantastic to see movement on this repo by you :-) feedback etc has been really appreciated and something that we are going to heavily rely on to ensure we are creating one solution for everyone :-)

**Comment by trevor-vaughan** [comment]
I don't think that PDK should be a dependency.

People have different frameworks and test in different ways. PDK may be a useful method for getting there for new users but should not be a hard requirement since it makes it more difficult for existing organizations to migrate.

**Comment by ekohl** [comment]
@tavilarion I personally agree. Now that Puppet 6 can no longer build modules I would like a very light gem that just implements the module building. PDK can depend on this to provide the same functionality. Litmus could also depend on just this gem. [puppet-blacksmith](https://github.com/voxpupuli/puppet-blacksmith) would add the dependency as well.

**Comment by tphoney** [comment]
Hi all, i have created [this](https://github.com/puppetlabs/puppet_litmus/blob/master/README.md#known-issues) which details what is going on. We are working to get this work merged, so things become more transparent and obvious. The ruby ecosystem 😞
