### ISSUE TITLE
Add additional information re: minimum Ruby version required to documentation

### ISSUE THREAD

**Issue by jdub55** [puppetlabs/puppet_litmus#74]
I am working through the installation of Litmus on my Mac and Ruby 2.2.9 does not appear to be sufficient to install all the dependencies (see snippet below) 

Installing i18n 1.6.0
Gem::InstallError: i18n requires Ruby version >= 2.3.0.

It would be helpful for new users to document the minimum expected Ruby version in the Wiki.

**Comment by jdub55** [comment]
And after upgrading to Ruby 2.3, I'm now seeing these versioning dependency issues. Is Ruby 2.4+ required?

++++++
Bundler could not find compatible versions for gem "ruby":
  In Gemfile:
    ruby

    puppet_litmus was resolved to 0.0.1, which depends on
      bolt (< 2.0.0, >= 0.21.4) was resolved to 1.14.0, which depends on
        ruby (~> 2.3)

    pdk was resolved to 1.10.0.pre, which depends on
      bundler (< 3.0.0, >= 1.15.0) was resolved to 1.16.1, which depends on
        ruby (>= 1.8.7)

    pdk was resolved to 1.10.0.pre, which depends on
      ffi (~> 1.9.0) was resolved to 1.9.25, which depends on
        ruby (>= 1.9)

    github_changelog_generator was resolved to 1.14.3, which depends on
      ruby (>= 1.9.3)

    github_changelog_generator was resolved to 1.14.3, which depends on
      octokit (~> 4.6) was resolved to 4.13.0, which depends on
        ruby (>= 2.0.0)

    rubocop-rspec was resolved to 1.32.0, which depends on
      rubocop (>= 0.60.0) was resolved to 0.65.0, which depends on
        parallel (~> 1.10) was resolved to 1.14.0, which depends on
          ruby (>= 2.2)

    pdk was resolved to 1.10.0.pre, which depends on
      ruby (>= 2.1.9)

    rubocop-rspec was resolved to 1.32.0, which depends on
      rubocop (>= 0.60.0) was resolved to 0.65.0, which depends on
        ruby (>= 2.2.2)

    rubocop-rspec was resolved to 1.32.0, which depends on
      ruby (>= 2.2.0)
++++++

**Comment by tphoney** [comment]
Hi @jdub55 we are currently working around the issues. this is particularly difficult due to the dependencies bolt has on puppet 5. and the pdk requiring a specific CRI version. 

so to help out short term, we are actively working on converting the motd module to use puppet_litmus 
https://github.com/puppetlabs/puppetlabs-motd/pull/200/files#diff-8b7db4d5cc4b8f6dc8feb7030baa2478

once we get a release of the pdk with some gemspec magic, we can introduce pinning of PDK and Bolt into puppet_litmus's gemspec. making everything a lot easier

**Comment by tphoney** [comment]
I am going to write up the explanation of the limitations and the work arounds for them. 

many apologies for the problems you have seen.
