### ISSUE TITLE
name change

### ISSUE THREAD

**Issue by logicminds** [puppetlabs/puppet_litmus#82]
Consider changing the name to puppet-litmus before it is too late.

Everything else in the puppet toolchain is `puppet-<name>`.  It is a bit annoying to make that assumption and then be wrong.

Please update to use `-` instead of `_`

**Comment by ekohl** [comment]
:-1: on this. `puppet-<name>` are usually puppet modules. Gems have the convention of underscores. IMHO this subtle distinction is actually a feature. In Voxpupuli we have puppet-blacksmith and it's always a pain to deal with when breaking the convention.

**Comment by tphoney** [comment]
'-' or dashes are horrible in the ruby ecosystem. Underscores make more sense, i played with both and underscores won, especially with gem names.

**Comment by trevor-vaughan** [comment]
We handled this in SIMP-space by doing the following since GitHub doesn't have subgroups like GitLab:

* Rubygems => `rubygem-<gem_name>`
* Puppet Modules => `pupmod-<author>-<module_name>`

Keeps things completely clean when you pull things in from other people as well.

**Comment by dhollinger** [comment]
@ekohl the tricky part is that `-` and `_` have different meanings in Ruby for namespacing and I think it's important to keep the repo name as close to the gem name as possible

**Comment by trevor-vaughan** [comment]
@dhollinger That works until `puppetlabs` takes over the `puppet` namespace at some point and/or Vox wants to import the repo.

Prefacing with a human-friendly addition is the only way I know of to work around this globally.

**Comment by ekohl** [comment]
> @ekohl the tricky part is that `-` and `_` have different meanings in Ruby for namespacing and I think it's important to keep the repo name as close to the gem name as possible

That's what I was trying to say. Ruby gems prefer underscores and you want the github repo to match the gem name. Hence why I think the current situation is correct.

**Comment by logicminds** [comment]
I had no idea there was even an official convention for ruby gem naming.  Is this even documented?  Suppose naming doesn't matter now since it is a crapshoot when loading various gems.

Just don't make it 

gem puppet_litmus

And then ' require puppet-litmus'

I suppose we can close this topic since it won't be changing.

**Comment by ekohl** [comment]
The readme currently does state:
> gem install puppet-litmus

That's inconsistent with the actual gem name so that should be fixed before closing this :)

**Comment by tphoney** [comment]
@logicminds there was no convention, i stumbled across this naming pattern by accident. But i ended up sticking with it. thanks @ekohl for pointing out the mistake in the readme. That is fixed now. 

I am closing this ticket. thanks for the discussion.
