### ISSUE TITLE
Converting module following wiki seems to fail if BUNDLE_PATH is not set

### ISSUE THREAD

**Issue by albatrossflavour** [puppetlabs/puppet_litmus#88]
I followed [the instructions on the wiki](https://github.com/puppetlabs/puppet_litmus/wiki/Converting-a-module-to-use-Litmus#update-files) to convert one of my modules over to litmus.

I ran into the following error:

```4) os_patching module purge base class 
     On host 'localhost:2226'
     Failure/Error: apply_manifest_and_idempotent(pp_class_absent)
     NameError:
       uninitialized constant PuppetLitmus::Tempfile
       
     # ./vendor/bundle/ruby/2.5.0/gems/puppet_litmus-0.0.1/lib/puppet_litmus.rb:43:in 'create_manifest_file'
     # ./vendor/bundle/ruby/2.5.0/gems/puppet_litmus-0.0.1/lib/puppet_litmus.rb:62:in 'apply_manifest_and_idempotent'
     # ./spec/acceptance/os_patching_spec.rb:93:in `block (3 levels) in <top (required)>'
```

I initially worked around it by adding `require 'tempfile'` into `puppet_litmus.rb` and it did "solve" the problem.  I was concerned that I wasn't seeing it on the MOTD module that I converted earlier.

I tracked it down to a missing entry in `.bundle/config`.  The original one was :

```
---
BUNDLE_JOBS: "4"
```

I reverted my change to `puppet_litmus.rb` and changed `.bundle/config` to:
```
---
BUNDLE_JOBS: "4"
BUNDLE_PATH: ".bundle/gems"
```

This solved the problem, but I'll confess that I'm not sure why.

Might be worth adding to the wiki (or cluebat me with what I've missed!)

**Comment by tphoney** [comment]
thanks for creating the issue, i'll have a think and get back to you. the wonders of the ruby ecosystem

**Comment by tphoney** [comment]
does https://github.com/puppetlabs/puppet_litmus/pull/102 solve the other issue ?

**Comment by DavidS** [comment]
Hi @albatrossflavour 

I've just revamped the Getting Started guide as part of the move to a jekyll-based micro site at https://puppetlabs.github.io/litmus/ . This is now fully based on using the PDK which should mean all of the issues you've been running into being resolved.

Feel free to re-open this issue, or create a new one if you're still having troubles.
