### ISSUE TITLE
puppet-litmus use an on-premise vmpooler

### ISSUE THREAD

**Issue by mitchdubdub** [puppetlabs/puppet_litmus#97]
It would be nice if we could enter the url and api of the on-prem vmpooler into the puppet-litmus provisioning method; so as to acquire from the on-prem vmpooler a vm for spec testing with puppet-litmus.

**Comment by mitchdubdub** [comment]
I think this needs to be in https://github.com/puppetlabs/provision/blob/master/tasks/vmpooler.rb#L29 and L71?

**Comment by tphoney** [comment]
Agreed, this will require changes in the provision module and also in the litmus gem. would you prefer to pass a parameter to the provision rake task in litmus https://github.com/puppetlabs/puppet_litmus/blob/master/lib/puppet_litmus/rake_tasks.rb#L107 ? or use environment variables ?

**Comment by mitchdubdub** [comment]
environment variable

**Comment by tphoney** [comment]
Hey @mitchdubdub apologies for the delay. Does this look ok https://github.com/puppetlabs/provision/pull/43 ?

**Comment by tphoney** [comment]
This was merged, thanks for pointing this out.
